CREATE TABLE USER_INFO
(
    USER_NO NUMBER CONSTRAINT PK_USER_NO PRIMARY KEY,
    USER_ID VARCHAR2(50) CONSTRAINT UNIQUE_USER_ID UNIQUE,
    USER_PWD VARCHAR2(50)
);

COMMENT ON COLUMN USER_INFO.USER_NO IS '유저번호';
COMMENT ON COLUMN USER_INFO.USER_ID IS '유저아이디';
COMMENT ON COLUMN USER_INFO.USER_PWD IS '유저비밀번호';

CREATE SEQUENCE SEQ_USER
NOCACHE;