CREATE USER TODOLIST IDENTIFIED BY TODOLIST;

GRANT CONNECT, RESOURCE TO TODOLIST;

CREATE TABLE TODOLIST
(
    TODO_NUM NUMBER NOT NULL,
    TODO_LIST VARCHAR2(100) NOT NULL,
    TODO_CHECK CHAR(3) DEFAULT 'X' NOT NULL,
    PRIMARY KEY(TODO_NUM)
);

CREATE SEQUENCE SEQ_TODO;